@ Generated by gcc 2.95.3 20010315 (release) for ARM/elf
	.file	"crt0.c"
@ GNU C version 2.95.3 20010315 (release) (arm-linux) compiled by GNU C version 2.95.2 20000220 (Debian GNU/Linux).
@ options passed:  -fverbose-asm
@ options enabled:  -fpeephole -ffunction-cse -fkeep-static-consts
@ -freg-struct-return -fsjlj-exceptions -fcommon -fverbose-asm -fgnu-linker
@ -fargument-alias -fident -mapcs-32 -mshort-load-bytes
@ -mno-short-load-words

gcc2_compiled.:
.text
	.align	2
	.global	__gccmain
	.type	 __gccmain,function
__gccmain:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, current_function_anonymous_args = 0
	mov	ip, sp
	stmfd	sp!, {fp, ip, lr, pc}
	sub	fp, ip, #4
.L2:
	ldmea	fp, {fp, sp, pc}
.Lfe1:
	.size	 __gccmain,.Lfe1-__gccmain
	.align	2
	.global	crt0
	.type	 crt0,function
crt0:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, current_function_anonymous_args = 0
	mov	ip, sp
	stmfd	sp!, {r4, fp, ip, lr, pc}
	sub	fp, ip, #4
	bl	timer_init
	bl	malloc_init
	ldr	r3, .L6
	ldr	r2, [r3, #12]
	cmp	r2, #0
	beq	.L4
	ldr	r3, .L6
	ldr	r4, [r3, #12]
	mov	lr, pc
	mov	pc, r4
.L4:
	mov	r0, #0
	mov	r1, #0
	bl	main
	b	.L5
.L7:
	.align	2
.L6:
	.word	stdfn
.L5:
.L3:
	ldmea	fp, {r4, fp, sp, pc}
.Lfe2:
	.size	 crt0,.Lfe2-crt0
	.ident	"GCC: (GNU) 2.95.3 20010315 (release)"
